# Установка базового образа
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Установка образа SDK для сборки
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "DailyFoodProject.csproj"
RUN dotnet build "DailyFoodProject.csproj" -c Release -o /app/build

# Выполнение сборки
FROM build AS publish
RUN dotnet publish "DailyFoodProject.csproj" -c Release -o /app/publish

# Использование образа ASP.NET Core
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DailyFoodProject.dll"]